### PR TITLE
Strip table tags whilst processing internal text as markdown

### PR DESCRIPTION
**Pull request by JonRowe**
This turns tables into something more intelligible.

### CODE REVIEW

**Comment by travo** [comment]
Nifty. The branch looks okay to me, I'll let @yob take a look too.

**Comment by yob** [comment]
This works as advertised, although I'll admit to being skeptical that this process will make all tables more intelligible in all cases.

Hopefully it improves the specific kinds of tables that we see in jobs though - is there a jobs table I can test with?

**Comment by JonRowe** [comment]
I almost have the PR ready that shows the jobs uscase but I need a passing master first

**Comment by yob** [comment]
I've checked a sample that demonstrates stripping of tables, and it works as described. Cheers! :+1:

**Pull request merged**
