### PR TITLE
Modernise specs

### PR DESCRIPTION
**Pull request by JonRowe**
This upgrades RSpec in stages, makes some best practise improvements to the specs (removing manual requires of the spec helper, turning on zero monkey patching mode, randomising the ordering), then improves the specs by adding descriptions and a few custom matchers for readability.

Additionally this upgrades parslet to the latest version.

### CODE REVIEW

**Comment by yob** [comment]
Looks good to me! Can you add a brief description to help out future us?

**Comment by JonRowe** [comment]
Done, and I've just removed a now redundant file

**Comment by JonRowe** [comment]
And green again

**Comment by yob** [comment]
:+1:

**Pull request merged**
